mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('volunteering/', include('volunteering.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('sitecore.urls')),
]

mysite/resources/urls.py
from django.urls import path
from . import views
from resources.views import (
    LearningResourceListView, LearningResourceCreateView, 
    LearningResourceUpdateView, LearningResourceDeleteView,
    LearningResourceDetailView, UserLearningResourceListView,
)

app_name = 'resources'

urlpatterns = [
    path('', views.index, name='index'), 
    path('all/', LearningResourceListView.as_view(), name='all_learning_resources'),
    path('my_resources/', UserLearningResourceListView.as_view(), name='my_learning_resources'),
    path('new/', LearningResourceCreateView.as_view(), name='resource_create'),
    path('<int:pk>/', LearningResourceDetailView.as_view(), name='resource_detail'),
    path('<int:pk>/update/', LearningResourceUpdateView.as_view(), name='resource_update'),
    path('<int:pk>/delete/', LearningResourceDeleteView.as_view(), name='resource_delete' ),
]

mysite/users/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name='profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', success_url=reverse_lazy('users:password_reset_done'), email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/resources/templates/resources/base.html
{% extends "sitecore/base.html" %}
{% block appnav %}

<nav class="navbar navbar-light navbar-expand-md navigation-clean">
    <div class="container">
        <a class="navbar-brand" href="{% url 'resources:index' %}" style="font-size: 18px;">Resources <i class="fa fa-gear" style="color: rgb(28,153,84);"></i></a>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'resources:resource_create' %}">add resource</a></li>
        </ul>
        </div>
    </div>
</nav>

{% endblock appnav %}

mysite/resources/templates/resources/index.html
{% extends "resources/base.html" %}
{% load static %}
{% block content %}
<header class="text-center" style="color: rgb(28,153,84);">
    <h2>Welcome to the Resources App</h2>
    <img src="{% static 'sitecore/img/short_banner.png' %}">
</header>
<div class="card" style="margin: 10px;">
    <div class="card-header" style="color: rgb(33, 37, 41);background: rgba(28,153,84,0.4);">
        <a href="{% url 'resources:all_learning_resources' %}"><h5 class="mb-0" style="color: #ffffff;">All Resource Lists</h5></a>
    </div>
    <div class="card-body">
        <p class="card-text">View all currently available resource lists, search, or browse by subject.&nbsp;</p>
    </div>
</div>
{% if user_tracks %}
<div class="card" style="margin: 10px;">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <a href="{% url 'resources:my_learning_resources' %}"><h5 class="mb-0" style="color: #ffffff;">My Resource Lists&nbsp;<button class="btn btn-secondary" type="button">{{ user_tracks }}</button></h5></a>
    </div>
    <div class="card-body">
        <p class="card-text">View the resource lists you have created, are currently managing, or are subscribed to.</p>
    </div>
</div>
{% endif %}
{% endblock content %}

mysite/resources/templates/resources/learning_resources_list.html
{% extends "resources/base.html" %}
{% block content %}

<header class="text-center">
    <h1 class="text-black-50">Learning Resources</h1>
</header>
{% if learning_resources  %}

<div class="card">
    <div class="card-header">
        {% if user_resources %}
        <h5 class="mb-0">{{ request.user|title }}'s Learning Resources</h5>
        {% else %}
        <h5 class="mb-0">All Learning Resources</h5>
        {% endif %}
    </div>
    <div class="card-body">
        {% if user_resources %}
        {% if learning|length %}
        <p class="card-text">Click on a learning resource to read more about it, modify or delete it, or go to the resource list itself.</p>
        {% else %}
        <p class="card-text">You don't have any learning resources yet. Go to the "<a href="{% url 'resources:resource_create' %}">add resource</a>" link to add your first resource.</p>
        {% endif %}
        {% else %}
        <p class="card-text">Click on a learning resource to read more about it or go to the resource list itself.</p>
        {% endif %}
    </div>
</div>
{% for resource, color in  learning_resources %}
</div class="container">
<div class="card">
    <div class="card-body" style="background: rgba({{ color.0 }}, {{ color.1 }}, {{ color.2 }}, 0.4);">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <a class="text-muted" href="{% url 'resources:resource_detail' resource.pk %}">{{ resource.title }}</a>
                        <p class="text-white">{{ resource.tagline }}</p>
                    </div>
                    <div class="col-4">
                        {% for category_tag in resource.tags.all %}
                        <button class="btn btn-outline-dark btn-sm" type="button">{{ category_tag }}</button>
                        {% endfor %}
                    </div>
                    <div class="col-2">
                        <a href="{% url 'resources:resource_detail' resource.pk %}" class="btn btn-secondary btn-lg">View</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
There are no volunteer projects
{% endif %}

{% if learning_resources %}
    {% for resource in learning_resources %}
    <a href="{% url 'resources:resource_detail' resource.pk %}">{{ resource.title }}</a>
    <small><a href="{{ resource.notion_link }}" target="_blank">[Open Link]</a></small>
    <br>
    <hr>
    {% endfor %}
{% else %}
    <p>No Learning Tracks</p>

{% endif %}
{% endblock content %}

mysite/resources/templates/resources/learningresource_confirm_delete.html
{% extends "resources/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Delete Resource</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0"><a style="color: black;" href="{% url 'resources:resource_detail' object.pk %}">{{ object.title|title }}</a></h5>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">Resource Information</h5>
        <ul class="list-group">
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.title }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.notion_link }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.tagline }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.description }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i>
                <span>
                    {% for tag in object.tags.all %}
                    <button class="btn btn-outline-dark btn-sm" type="button">{{ tag }}</button>
                    {% endfor %}
                </span>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">Are you sure you want to delete this resource?</h2>
                            <div class="form-group">{{ form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><strong>Permanently Delete</strong> {{ object.title }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'resources:all_learning_resources' %}">back to <strong>ALL</strong> Resources</a></div>
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'resources:my_learning_resources' %}">back to <strong>MY</strong> Resources</a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/resources/templates/resources/learningresource_detail.html
{% extends "resources/base.html" %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Resource Detail</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h5 class="mb-0">{{ object.title|title }}</h5>
                </div>
                {% if can_edit %}
                <div class="col-4 text-center">
                    <a href="{% url 'resources:resource_update' object.pk %}" class="btn btn-outline-secondary btn-sm" role="button">Edit Resource</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">Resource Information</h5>
        <ul class="list-group">
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.title }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.notion_link }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.tagline }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.description }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i>
                <span>
                    {% for tag in object.tags.all %}
                    <button class="btn btn-outline-dark btn-sm" type="button">{{ tag }}</button>
                    {% endfor %}
                </span>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <p>{{ object.notion_link }}</p>
                </div>
                <div class="col-4 text-center"><a href="{{ object.notion_link }}" class="btn btn-secondary" role="button" target="_blank">Visit Resource Link</a></div>
            </div>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a href="{% url 'resources:all_learning_resources' %}" class="btn btn-outline-secondary" role="button" style="border-width: 2px;">back to <strong>ALL</strong> Resources</a></div>
                {% if user_tracks %}
                <div class="col-6"><a href="{% url 'resources:my_learning_resources' %}" class="btn btn-outline-secondary" role="button" style="border-width: 2px;">back to <strong>MY</strong> Resources</a></div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

mysite/resources/templates/resources/learningresource_form.html
{% extends "resources/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    {% if object %}
    <h1 class="text-black-50">Update Resource</h1>
    {% else %}
    <h1 class="text-black-50">Add New Resource</h1>
    {% endif %}
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                {% if object %}
                <div class="col-8">
                    <h5 class="mb-0"><a style="color: black;" href="{% url 'resources:resource_detail' object.pk %}">{{ object.title|title }}</a></h5>
                </div>
                <div class="col-4 text-center">
                    <a href="{% url 'resources:resource_delete' object.pk %}" class="btn btn-outline-danger btn-sm" role="button">Delete Resource</a>
                </div>
                {% else %}
                <div class="col">
                    <h5 class="mb-0">New Resource</h5>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% if object %}
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">Resource Information</h5>
        <ul class="list-group">
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.title }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.notion_link }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.tagline }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ object.description }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i>
                <span>
                    {% for tag in object.tags.all %}
                    <button class="btn btn-outline-dark btn-sm" type="button">{{ tag }}</button>
                    {% endfor %}
                </span>
            </li>
        </ul>
    </div>
    {% endif %}
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">Resource Form</h2>
                            <div class="form-group">{{ form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        {% if object %}
                        <button type="submit" class="btn btn-secondary"><strong>Update</strong> this resource</button>
                        {% else %}
                        <button type="submit" class="btn btn-secondary"><strong>Add</strong> resource</button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'resources:all_learning_resources' %}">back to <strong>ALL</strong> Resources</a></div>
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'resources:my_learning_resources' %}">back to <strong>MY</strong> Resources</a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}