mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('volunteering/', include('volunteering.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('sitecore.urls')),
]

mysite/users/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name='profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', success_url=reverse_lazy('users:password_reset_done'), email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/volunteering/urls.py
from django.urls import path
from . import views
from .views import ProjectListView, ProjectDetailView

app_name = 'volunteering'

urlpatterns = [
    path('', views.index, name='index'),
    path('all/', ProjectListView.as_view(), name='all_volunteer_projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
]

mysite/volunteering/models.py
from django.db import models

class CategoryTag(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.title}'


class VolunteerProject(models.Model):
    title = models.CharField(max_length=255)
    tagline = models.CharField(max_length=255, default='No Tag Line', null=True)
    tags = models.ManyToManyField(CategoryTag)

    def __str__(self):
        return f'{self.title}'


class VolunteerProjectDetailCategory(models.Model):
    project = models.ForeignKey(VolunteerProject, on_delete=models.CASCADE)
    label = models.CharField(max_length=50)
    heading = models.CharField(max_length=150)
    position = models.IntegerField() # position of category within project post

    def __str__(self):
        return f'Category {self.position} "{self.heading}"- {self.project}'


class VolunteerProjectDetail(models.Model):
    detail_category = models.ForeignKey(VolunteerProjectDetailCategory, on_delete=models.CASCADE)
    text = models.TextField()
    position = models.IntegerField() # position of detail within category

    def __str__(self):
        return f'Detail {self.position} - {self.detail_category}'

mysite/volunteering/views.py
import random
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import (
    VolunteerProject, VolunteerProjectDetail, VolunteerProjectDetailCategory
)

def index(request):
    return render(request, 'volunteering/index.html')


class ProjectListView(ListView):
    model = VolunteerProject
    template_name = 'volunteering/volunteer_projects_list.html'
    context_object_name = 'projects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        colors = self.get_colors(len(context['projects']))

        context['projects'] = zip(context['projects'], colors)
        return context

    def get_colors(self, list_length):
        colors = []

        for item in range(list_length):
            green_color = [28, 153, 84]
            variance_coeff = 0.15
            new_color = []
            for component in green_color:
                value_range = [int(component - (component * variance_coeff)), int(component + (component * variance_coeff))]
                random_value = random.randint(*value_range)
                new_color.append(random_value)

            colors.append(new_color)
        return colors



class ProjectDetailView(DetailView):
    model = VolunteerProject
    template_name = 'volunteering/volunteer_project_detail.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.get_object()
        related_detail_categories = VolunteerProjectDetailCategory.objects.filter(
            project=project).order_by('position')
        details_structure = {}
        for category in related_detail_categories:
            related_details = VolunteerProjectDetail.objects.filter(
                detail_category=category).order_by('position').values_list('text', flat=True)
            details_structure[f'{category.heading}'] = related_details

        context['categories_detials'] = details_structure
        return context

mysite/volunteering/templates/volunteering/base.html
{% extends "sitecore/base.html" %}
{% block appnav %}
    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
        <div class="container">
            <a class="navbar-brand" href="{% url 'volunteering:index' %}" style="font-size: 18px;">Volunteering <i class="fa fa-gear" style="color: rgb(28,153,84);"></i></a>
            
            </div>
        </div>
    </nav>
{% endblock appnav %}

mysite/volunteering/templates/volunteering/index.html
{% extends "volunteering/base.html" %}
{% load static %}
{% block content %}
<header class="text-center" style="color: rgb(28,153,84);">
    <h2>Welcome to the Volunteering App</h2>
    <img src="{% static 'sitecore/img/short_banner.png' %}">
</header>
<div class="card" style="margin: 10px;">
    <div class="card-header" style="color: rgb(33, 37, 41);background: rgba(28,153,84,0.4);">
        <a href="{% url 'volunteering:all_volunteer_projects' %}"><h5 class="mb-0" style="color: #ffffff;">All Volunteer Projects</h5></a>
    </div>
    <div class="card-body">
        <p class="card-text">View all currently available volunteer projects, search, or browse by category.&nbsp;</p>
    </div>
</div>
{% if user_projects %}
<div class="card" style="margin: 10px;">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <a href="#"><h5 class="mb-0" style="color: #ffffff;">My Resource Lists</h5></a>
    </div>
    <div class="card-body">
        <p class="card-text">View the volunteer projectsyou have created, are currently managing, or have applied to.</p>
    </div>
</div>
{% endif %}
{% endblock content %}

mysite/volunteering/templates/volunteering/volunteer_project_detail.html
{% extends "volunteering/base.html" %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Volunteer Project Detail</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0">{{ project.title }}</h5>
                </div>
            </div>
        </div>
    </div>
    {% for category, detail_list in categories_detials.items %}
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">{{ category }}</h5>
        <ul class="list-group">
                {% for detail in detail_list %}
                <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ detail }}</span></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12"><a class="btn btn-secondary" role="button" href="#"><strong>Apply</strong> to manage this project</a></div>
            </div>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'volunteering:all_volunteer_projects' %}">back to <strong>All</strong> Projects</a></div>
                {% if user_projects %}
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="#">back to <strong>My</strong> Projects</a></div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/volunteering/templates/volunteering/volunteer_projects_list.html
{% extends "volunteering/base.html" %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Volunteer Projects</h1>
</header>
<div class="card">
    <div class="card-header">
        <h5 class="mb-0">All Volunteer Projects</h5>
    </div>
    <div class="card-body">
        <p class="card-text">Click on a project to read the full project description and apply to manage it. </p>
    </div>
</div>
{% if not projects %}
    There are no volunteer projects
{% else %}
    {% for project, color in  projects %}
        </div class="container">
            <div class="card">
                <div class="card-body" style="background: rgba({{ color.0 }}, {{ color.1 }}, {{ color.2 }}, 0.4);">
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <a class="text-muted" href="{% url 'volunteering:project_detail' project.pk %}">{{ project.title }}</a>
                                    <p class="text-white">{{ project.tagline }}</p>
                                </div>
                                <div class="col-4">
                                    {% for category_tag in project.tags.all %}
                                    <button class="btn btn-outline-dark btn-sm" type="button">{{ category_tag }}</button>
                                    {% endfor %}
                                </div>
                                <div class="col-2">
                                    <a href="{% url 'volunteering:project_detail' project.pk %}" class="btn btn-secondary btn-lg">View</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock content %}