mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('volunteering/', include('volunteering.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('sitecore.urls')),
]

mysite/resources/urls.py
from django.urls import path
from . import views
from resources.views import (
    LearningResourceListView, LearningResourceCreateView, 
    LearningResourceUpdateView, LearningResourceDeleteView,
    LearningResourceDetailView, UserLearningResourceListView,
)

app_name = 'resources'

urlpatterns = [
    path('', views.index, name='index'), 
    path('all/', LearningResourceListView.as_view(), name='all_learning_resources'),
    path('my_resources/', UserLearningResourceListView.as_view(), name='my_learning_resources'),
    path('new/', LearningResourceCreateView.as_view(), name='resource_create'),
    path('<int:pk>/', LearningResourceDetailView.as_view(), name='resource_detail'),
    path('<int:pk>/update/', LearningResourceUpdateView.as_view(), name='resource_update'),
    path('<int:pk>/delete/', LearningResourceDeleteView.as_view(), name='resource_delete' ),
]

mysite/sitecore/urls.py
from django.urls import path
from . import views
from .views import FAQListView

app_name = 'sitecore'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/', FAQListView.as_view(), name='faq'),
    path('about/<slug:program_name>/', views.about_program, name='about-program-detail'),
]

mysite/users/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name='profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', success_url=reverse_lazy('users:password_reset_done'), email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/volunteering/urls.py
from django.urls import path
from . import views
from .views import ProjectListView, ProjectDetailView

app_name = 'volunteering'

urlpatterns = [
    path('', views.index, name='index'),
    path('all/', ProjectListView.as_view(), name='all_volunteer_projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
]

mysite/sitecore/models.py
from django.db import models
from django.utils.text import slugify

class Page(models.Model):
    title = models.CharField(max_length=50)
    label = models.SlugField(max_length=50, unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.label:
            self.label = slugify(self.title)
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.label}'


class SectionTitle(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    position = models.IntegerField(default=0) #position of section witin page

    def __str__(self):
        return f'{self.title} ({self.page}, position {self.position})'


class CopyText(models.Model):
    title = models.ForeignKey(SectionTitle, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    position = models.IntegerField(default=0) #position of copy within section

    def __str__(self):
        
        return f'{self.text[:30]}, {self.title}'


class FrequentQuestion(models.Model):
    question_text = models.CharField(max_length=150)
    answer_text = models.TextField()
    votes = models.IntegerField()

    def __str__(self):
        return f'{self.votes}: {self.question_text[:10]}'
        

mysite/sitecore/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from .models import FrequentQuestion, CopyText, Page, SectionTitle

def index(request):
    about_pages = Page.objects.all()
    context = {'about_pages': about_pages}
    return render(request, 'sitecore/index.html', context)

def about_program(request, program_name):
    page = Page.objects.get(label=program_name)
    section_structures = []
    sections = SectionTitle.objects.filter(page__label=program_name).order_by('position')
    for section in sections:
        section_copy_items = CopyText.objects.filter(title=section).order_by('position')
        section_structures.append((section, section_copy_items))
    
    context = {'sections': section_structures, 'page': page}
    return render(request, 'sitecore/about_program.html', context)


class FAQListView(ListView):
    model = FrequentQuestion
    template_name = 'sitecore/faq.html'
    context_object_name = 'faqs'
    ordering = ['votes']

mysite/sitecore/templates/sitecore/about_program.html
{% extends "sitecore/base.html" %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">About Our {{ page.title|title }} Program</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0">{{ project.title }}</h5>
                </div>
            </div>
        </div>
    </div>
    {% for section, copy_items in sections %}
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">{{ section.title.title }}</h5>
        <ul class="list-group">
                {% for item in copy_items %}
                <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ item.text }}</span></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12"><a class="btn btn-secondary" target="_blank" role="button" href="https://www.readytechpro.org/community"><strong>Join</strong> us</a></div>
            </div>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'sitecore:index' %}">back to <strong>home</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/sitecore/templates/sitecore/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Ready Tech Pro</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static 'sitecore/css/Navigation-Clean.css' %}">
<link rel="stylesheet" href="{% static 'sitecore/css/Footer-Clean.css' %}">
<link rel="stylesheet" href="{% static 'sitecore/css/styles.css' %}">
</head>
<body>

{% if messages %}
{% for message in messages %}
<div role="alert" class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <span>{{ message }}</span>
</div>
{% endfor %}
{% endif %}


{% if user.is_authenticated %}
<nav class="navbar navbar-light navbar-expand-md navigation-clean">
    <div class="container">
        <a class="navbar-brand" href="{% url 'sitecore:index' %}">Ready Tech Pro <i class="fa fa-home" style="color: rgb(28,153,84);"></i></a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">log out</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:profile' %}">profile</a></li>
            </ul>
        </div>
    </div>
</nav>
{% else %}
<div role="alert" class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <span><a href="{% url 'users:login' %}"><strong>Log in</strong></a> to access customized features.</span>
</div>
<nav class="navbar navbar-light navbar-expand-md navigation-clean">
    <div class="container"><a class="navbar-brand" href="{% url 'sitecore:index' %}">Ready Tech Pro</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <i class="fa fa-home" style="color: rgb(28,153,84);"></i>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">log in</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">register</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endif %}
    {% block appnav %}
    {% endblock appnav %}
    {% block content %}
    <p>no page content</p>
    {% endblock content %}

    <footer class="footer-clean">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-4 col-md-3 item">
                    <h3>Apps</h3>
                    <ul>
                        <li><a href="{% url 'resources:index' %}">Resources</a></li>
                        <li><a href="{% url 'volunteering:index' %}">Volunteering</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="{% url 'sitecore:index' %}">Programs</a></li>
                        <li><a href="{% url 'sitecore:faq' %}">FAQs</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3>More</h3>
                    <ul>
                        <li><a href="https://www.readytechpro.org">Static Site</a></li>
                        <li><a href="https://www.readytechpro.org/community">Join Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 item social">
                    <a href="https://github.com/readytechpro"><i class="icon ion-social-github"></i></a>
                    <a href="{% url 'sitecore:faq' %}"><i class="icon ion-social-usd"></i></a>
                    <a href="mailto:info@readytechpro.org"><i class="icon ion-email"></i></a>
                    <a href="https://www.readytechpro.org/community"><i class="icon ion-chatboxes"></i></a>
                    <p class="copyright">Ready Tech Pro © 2021</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/sitecore/templates/sitecore/faq.html
{% extends "sitecore/base.html" %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Frequently Asked Questions</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0"> </h5>
                </div>
            </div>
        </div>
    </div>
    {% for faq in faqs %}
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">{{ faq.question_text }}</h5>
        <ul class="list-group">
                <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ faq.answer_text }}</span></li>
            </ul>
        </div>
    {% endfor %}
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12"><a class="btn btn-secondary" target="_blank" role="button" href="https://www.readytechpro.org/community"><strong>Join</strong> us</a></div>
            </div>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'sitecore:index' %}">back to <strong>home</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/sitecore/templates/sitecore/index.html
{% extends "sitecore/base.html" %}
{% load static %}
{% block content %}

<header class="text-center" style="color: rgb(28,153,84);">
    <h1>Welcome to Ready Tech Pro</h1><img src="{% static 'sitecore/img/banner.png' %}">
</header>
<div class="card">
    <div class="card-header">
        <h4>App Links</h4>
    </div>
    <div class="card-body">
        <p class="card-text">Here are some apps that are currently under development. Please check them out!&nbsp;</p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-3"><a href="{% url 'resources:index' %}"><img class="img-thumbnail img-fluid" src="{% static 'sitecore/img/accept-request.png' %}"></a></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'resources:index' %}"><h4 class="card-title" style="color: #1c9954;">Resoureces Portal</h4></a>
                    <h6 class="text-muted card-subtitle mb-2">A system for discovering, organizing, and sharing online learning resources.&nbsp;</h6>
                    <p class="card-text">Discover, organize, personalize, and share skill-based lists of online educational resources that are curated for our community.</p>
                    <a class="card-link" href="{% url 'resources:index' %}">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-3"><a href="{% url 'volunteering:index' %}"><img class="img-thumbnail img-fluid" src="{% static 'sitecore/img/joy.png' %}"></a></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'volunteering:index' %}"><h4 class="card-title" style="color: #1c9954;">Volunteering Portal</h4></a>
                    <h6 class="text-muted card-subtitle mb-2">Contribute to volunteer projects and help develop Ready Tech Pro</h6>
                    <p class="card-text">Ready Tech Pro needs your help! Please consider applying for one of these low-commitment volunteer projects and contribute to the development of our nonprofit platform.</p>
                    <a class="card-link" href="{% url 'volunteering:index' %}">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% if about_pages %}
<div class="card">
    <div class="card-header">
        <h4>About Our Programs in Development</h4>
    </div>
    <div class="card-body">
        <p class="card-text">These are the main programs that we are currently developing for our community.&nbsp;</p>
    </div>
</div>
{% for page in about_pages %}
<div class="container">
    <div class="row">
        <div class="col-3"><a href="{% url 'sitecore:about-program-detail' page.label %}"><img class="img-thumbnail img-fluid" src="{% static 'sitecore/img/placeholder.png' %}"></a></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'sitecore:about-program-detail' page.label %}"><h4 class="card-title" style="color: #1c9954;">{{ page.title }}</h4></a>
                    <h6 class="text-muted card-subtitle mb-2">Program summary line&nbsp;</h6>
                    <p class="card-text">Program short description.</p>
                    <a class="card-link" href="{% url 'sitecore:about-program-detail' page.label %}">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
<div class="card">
    <div class="card-header">
        <h4>More</h4>
    </div>
    <div class="card-body">
        <p class="card-text">Read and submit questions to our FAQs&nbsp;</p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-3"><img class="img-thumbnail img-fluid" src="{% static 'sitecore/img/faq.png' %}"></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'sitecore:faq' %}"><h4 class="card-title" style="color: #1c9954;">FAQs</h4></a>
                    <h6 class="text-muted card-subtitle mb-2">Frequently Asked Questions</h6>
                    <p class="card-text">Visit our FAQ page to learn more.</p>
                    <a class="card-link" href="{% url 'sitecore:faq' %}">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}