mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('volunteering/', include('volunteering.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('sitecore.urls')),
]

mysite/resources/urls.py
from django.urls import path
from . import views
from resources.views import (
    LearningResourceListView, LearningResourceCreateView, 
    LearningResourceUpdateView, LearningResourceDeleteView,
    LearningResourceDetailView, UserLearningResourceListView,
)

app_name = 'resources'

urlpatterns = [
    path('', views.index, name='index'), 
    path('all/', LearningResourceListView.as_view(), name='all_learning_resources'),
    path('my_resources/', UserLearningResourceListView.as_view(), name='my_learning_resources'),
    path('new/', LearningResourceCreateView.as_view(), name='resource_create'),
    path('<int:pk>/', LearningResourceDetailView.as_view(), name='resource_detail'),
    path('<int:pk>/update/', LearningResourceUpdateView.as_view(), name='resource_update'),
    path('<int:pk>/delete/', LearningResourceDeleteView.as_view(), name='resource_delete' ),
]

mysite/users/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name='profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', success_url=reverse_lazy('users:password_reset_done'), email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.core.files.storage import default_storage as storage

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.__resize_image()

    def __resize_image(self):
        MAX_WIDTH = 300
        MAX_HEIGHT = 600
        with Image.open(self.image) as img:
            if img.width > MAX_WIDTH or img.height > MAX_HEIGHT:
                resize_ratio = min(
                    (MAX_WIDTH / img.width), (MAX_HEIGHT / img.height))
                output_size = (int(img.width * resize_ratio), int(img.height * resize_ratio))
                img = img.resize(output_size)

            with storage.open(self.image.name, "w") as file_handler:
                img.save(file_handler, 'png')
            

mysite/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

    def clean_image(self):
        MAX_BYTES = 6 * 1024 * 1024
        image = self.cleaned_data['image']
        file_size = image.size
        if file_size > MAX_BYTES:
            raise ValidationError(
                f'Image too large to upload. The maximum upload size is \
                    {(MAX_BYTES / 1024 / 1024):.2f} MB, and your \
                    {(file_size / 1024 / 1024):.2f} MB image exceeds that \
                    limit. Navigate to this page to try again.'
                )
        else:
            return image

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ProfileUpdateForm, UserRegisterForm, UserUpdateForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'A new Ready Tech Pro account has been created for {username}. You can now log in.')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', context={'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"{request.user.username}'s accont has been updated")
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context=context)

mysite/users/templates/users/login.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Sign in to Your Ready Tech Pro Account</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0"> </h5>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            {% if form %}
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">sign in</h2>
                            <div class="form-group">{{ form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-secondary"><strong>Log In</strong></button>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'users:password_reset' %}">Forgot your password? <strong>Reset</strong></a></div>
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'users:register' %}">Need an account? <strong>Register</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "sitecore/base.html" %}
{% block content %}
<div>
    <h2>You have been logged out</h2>
    <div>
        <p>Log in again</p>
        <a href="{% url 'users:login' %}">Log in</a>
    </div>
</div>
{% endblock content %}

mysite/users/templates/users/password_reset.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Request Password Reset</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0"> </h5>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            {% if form %}
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">reset your password</h2>
                            <div class="form-group">{{ form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-secondary"><strong>Send Reset Email</strong></button>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'users:register' %}">Need an account? <strong>Register</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/users/templates/users/password_reset_complete.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <p>Your Password has been reset.</p>
    <div>
        <p>Sign in to your account with your new password:</p>
        <a href="{% url 'users:login' %}">Sign in</a>
    </div>
</div>
{% endblock content %}

mysite/users/templates/users/password_reset_confirm.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div>
            <button type="submit">reset password</button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/users/templates/users/password_reset_done.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <p>An email has been sent with instructions to reset your password.</p>
</div>
{% endblock content %}

mysite/users/templates/users/password_reset_email.html
  
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

mysite/users/templates/users/profile.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">{{ user.username }}'s User Profile</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0">{{ user.username }}</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col text-center" style="background: rgba(28,153,84,0.1);"><img class="rounded img-fluid" src="{{ user.profile.image.url }}" width="500" height="500"></div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h5 style="color: rgb(28,153,84);">User Information</h5>
        <ul class="list-group">
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ user.username }}</span></li>
            <li class="list-group-item"><i class="fa fa-check-circle-o" style="margin: 5px;color: #1c9954;"></i><span>{{ user.email }}</span></li>
        </ul>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">update your information</h2>
                            <div class="form-group">{{ u_form|crispy }}</div>
                            <div class="form-group">{{ p_form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-secondary"><strong>Update</strong> my user profile</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="#">go to my <strong>Volunteer Projects</strong></a></div>
                <div class="col-6"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'resources:my_learning_resources' %}">go to my <strong>Resources</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/users/templates/users/register.html
{% extends "sitecore/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="text-center">
    <h1 class="text-black-50">Sign Up for a Ready Tech Pro Account</h1>
</header>
<div class="card border-dark" style="margin: 10px;border-radius: 5px;border-width: 1px;box-shadow: 1px 1px 2px 1px rgba(28,153,84,0.8);">
    <div class="card-header" style="background: rgba(28,153,84,0.4);">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="mb-0"> </h5>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            {% if form %}
            <div class="row">
                <div class="col" style="background: rgba(28,153,84,0.1);">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <h2 class="text-center">create your account</h2>
                            <div class="form-group">{{ form|crispy }}</div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-secondary"><strong>Sign Up</strong></button>
                    </div>
                </div>
            </div>
        </form>
        {% endif %}
        </div>
    </div>
</div>
<div class="card" style="margin: 0px;background: rgba(28,153,84,0.2);">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col"><a class="btn btn-outline-secondary" role="button" style="border-width: 2px;" href="{% url 'users:login' %}">Already registered? <strong>Log In</strong></a></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}